---
abstract: 'clustering data resolver'
author:
  - 'Atsushi Kobayashi <nekokak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::RuledCluster
name: Data-RuledCluster
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Load: 0
  Data::Util: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/p5-Data-RuledCluster.git
version: 0.04
